### ISSUE TITLE
Git/source installs fail before first turn because lazy imports are missing from Pi's extension graph

### ISSUE THREAD

**Issue by sofiane-fac** [fitchmultz/pi-cursor-sdk#228]
## Summary

`pi-cursor-sdk` 0.3.6 installed from GitHub, or loaded from a local checkout, fails before the first Cursor SDK request.

Pi displays a misleading authentication error:

```text
Cursor SDK request failed. The Cursor SDK API key may be missing, invalid, or unauthorized.
```

The API key is valid. The underlying error is a module-resolution failure:

```text
ResolveMessage: Cannot find module '@cursor/sdk' from '.../dist/cursor-sdk-runtime.js'
```

Pi's extension loader does not include dependencies reachable only through the runtime dynamic imports in the compiled `dist/` graph.

## Environment

- macOS 25.6.0 arm64
- Node.js 24.4.1
- pi 0.84.2
- pi-cursor-sdk 0.3.6
- @cursor/sdk 1.0.27
- Runtime: local Cursor SDK
- Installation sources tested:
  - GitHub installation
  - Local checkout via `pi -e .`

The same Cursor API key works with the npm release and successfully lists Cursor models.

## Reproduction with a GitHub install

```bash
pi install https://github.com/fitchmultz/pi-cursor-sdk
```

Start a fresh process:

```bash
pi --no-extensions \
  -e https://github.com/fitchmultz/pi-cursor-sdk \
  --no-context-files \
  --model cursor/grok-4.6:slow \
  --cursor-no-fast \
  --no-session \
  -p "Reply exactly: GITHUB_OK"
```

### Actual result

The process exits with:

```text
Cursor SDK request failed. The Cursor SDK API key may be missing, invalid, or unauthorized.
```

### Expected result

The provider starts a Cursor SDK run and prints:

```text
GITHUB_OK
```

## Reproduction with a local checkout

```bash
git clone https://github.com/fitchmultz/pi-cursor-sdk
cd pi-cursor-sdk
npm install
npm run build
```

Then:

```bash
pi --no-extensions \
  -e . \
  --no-context-files \
  --model cursor/grok-4.6:slow \
  --cursor-no-fast \
  --no-session \
  -p "Reply exactly: LOCAL_OK"
```

This fails with the same authentication-looking message.

## Underlying error

Enable provider diagnostics:

```bash
PI_CURSOR_SDK_EVENT_DEBUG=1 \
PI_CURSOR_SDK_EVENT_DEBUG_STDERR=1 \
PI_CURSOR_SDK_EVENT_DEBUG_DIR=/tmp/pi-cursor-sdk-module-repro \
pi --no-extensions \
  -e . \
  --no-context-files \
  --model cursor/grok-4.6:slow \
  --cursor-no-fast \
  --no-session \
  -p "Reply exactly: LOCAL_OK"
```

The generated `errors.jsonl` records:

```text
ResolveMessage: Cannot find module '@cursor/sdk' from '.../dist/cursor-sdk-runtime.js'
```

No Cursor SDK request is made, so this is not an authentication rejection.

## Cause

Two runtime-only import boundaries are omitted from Pi's static extension graph:

1. `src/cursor-sdk-runtime.ts` dynamically imports `@cursor/sdk`.
2. `src/cursor-pi-tool-bridge-server.ts` dynamically imports `./cursor-pi-tool-bridge-run.js`, which owns the runtime imports from `@modelcontextprotocol/sdk`.

After changing the SDK import to a static import, the next hidden dependency fails:

```text
Cannot find module '@modelcontextprotocol/sdk/server/index.js'
from '.../dist/cursor-pi-tool-bridge-run.js'
```

This confirms that the problem is dependency reachability in Pi's compiled extension graph.

## Locally verified fix

The local checkout works after:

- statically importing `@cursor/sdk` in `src/cursor-sdk-runtime.ts`;
- statically importing `CursorPiToolBridgeRunImpl` in `src/cursor-pi-tool-bridge-server.ts`.

After rebuilding, the isolated command completes successfully and prints:

```text
LOCAL_PATCH_OK
```

The generic provider-error handling should also avoid converting module-resolution failures into API-key errors.

**Comment by sofiane-fac** [comment]
Happy to open a PR!

**Comment by alexlee2046** [comment]
Confirming this on **the npm release too**, which the issue currently rules out ("The same Cursor API key works with the npm release"). Same error, same file, same misleading auth message.

## Environment

- macOS 26.0 (Darwin 27.0.0) arm64, pi 0.84.2, pi-cursor-sdk 0.3.6, @cursor/sdk 1.0.27
- Local Cursor runtime; the same API key works on pi-cursor-sdk 0.1.62 in the same install

## Repro from the registry (no GitHub/local checkout involved)

Both of these fail identically:

```bash
# a) plain npm into pi's package dir
cd ~/.pi/agent/npm && npm install pi-cursor-sdk@0.3.6

# b) the official path
pi install npm:pi-cursor-sdk@0.3.6
```

Then any Cursor turn dies in <1s with the API-key message. Instrumenting `sanitizeCursorProviderError` in the installed `dist/` gives the real error:

```
name=ResolveMessage code=ERR_MODULE_NOT_FOUND
msg=Cannot find module '@cursor/sdk' from '.../pi-cursor-sdk/dist/cursor-sdk-runtime.js'
```

Both a hoisted `@cursor/sdk@1.0.27` (in `~/.pi/agent/npm/node_modules/@cursor/sdk`) and a nested copy inside the package were present on disk for every run below.

## Data point that matches the two-boundary diagnosis

I tried patching **only** `cursor-sdk-runtime.ts` to a static `import * as CursorSdk from "@cursor/sdk"` and rebuilding `dist/`. It still failed — consistent with the second boundary (`cursor-pi-tool-bridge-server.ts` -> `@modelcontextprotocol/sdk`) described here. Both static imports are needed.

## Workarounds that do not work (Pi owns resolution entirely)

Worth recording so nobody else burns time on them:

| attempt | result |
|---|---|
| nested `@cursor/sdk@1.0.27` installed inside the package | `ERR_MODULE_NOT_FOUND` |
| `createRequire(import.meta.url).resolve("@cursor/sdk")` | `MODULE_NOT_FOUND` — `import.meta.url` is not a real file URL inside Pi's loader |
| `createRequire("<real absolute path to package.json>")("@cursor/sdk")` | `MODULE_NOT_FOUND` — no filesystem walk happens at all |
| dynamic import of an absolute `file://` URL to `@cursor/sdk/dist/esm/index.js` | the SDK module loads, then **its own** bare `@bufbuild/protobuf` fails the same way |

That last row is probably the same surface as #233.

## +1 on the error mapping

The message users actually see is `GENERIC_CURSOR_SDK_ERROR_MESSAGE`, which `sanitizeCursorProviderError` returns for anything `isGenericErrorMessage()` considers uninformative. A `ResolveMessage` / `ERR_MODULE_NOT_FOUND` falls into that bucket, so a module-resolution failure is reported as "your API key may be missing, invalid, or unauthorized". I spent a long time chasing credentials — including verifying that the key resolved correctly all the way into `requireCursorApiKey` — before instrumenting the sanitizer. Classifying `ERR_MODULE_NOT_FOUND` / `ResolveMessage` separately would have made this immediate.

Rolled back to 0.1.62, which works.

**Comment by SchlaftGut0-1** [comment]
Confirming on **Linux x86_64 with the compiled pi binary and the npm release** — same `ResolveMessage`, same misleading auth message, and I have a working workaround plus a deeper root-cause read that I hope saves the maintainer some time.

## Environment

- Arch Linux x86_64, pi **0.84.2 and 0.84.3** (compiled Bun binary via mise), pi-cursor-sdk **0.3.6** (npm release), @cursor/sdk 1.0.27
- The same Cursor API key authenticates fine against `api.cursor.com/v1/models` (HTTP 200), works through `Cursor.models.list()`, and a standalone `cursor-agent -p` run with the same key completes normally — so this is definitively not an auth rejection.

## Deeper root cause

Pi's extension loader (`packages/coding-agent/src/core/extensions/loader.ts`) creates jiti with `virtualModules: VIRTUAL_MODULES, tryNative: false` when running as a compiled binary / bundled Node build. `VIRTUAL_MODULES` only maps the host peers (`@earendil-works/*`, `typebox`). Anything else reachable through a **runtime** dynamic import is outside the static graph, and resolution fails with `ResolveMessage`. This matches earendil-works/pi#6455.

Three findings from instrumenting the installed `dist/`:

1. All three failing import sites are runtime-only boundaries:
   - `dist/cursor-sdk-runtime.js` → `import("@cursor/sdk")`
   - `dist/cursor-session-store.js` → `import("@cursor/sdk/sqlite")`
   - `dist/cursor-pi-tool-bridge-run.js` → static imports of `@modelcontextprotocol/sdk/server/index.js`, `server/streamableHttp.js`, `types.js`
2. The `createRequire()` / `require.resolve()` escape hatch does **not** bypass the loader here: patching `loadCursorSdk()` to `require("@cursor/sdk")` still fails with the same `ResolveMessage`, now with `importKind: "require-call"`. That also means `resolveBundledCursorRipgrepPath()` likely fails silently (its `catch` swallows it) on this class of installs.
3. Cold-boot discovery fails for the same reason; a warm `cursor-sdk-model-list.json` cache (key-fingerprint match) masks it at startup, which makes the turn failure look even more like an auth problem. Also worth noting: calling `sanitizeCursorProviderError()` directly with the bare `ResolveMessage` does **not** reproduce the auth wording (it returns the scrubbed module-not-found text), so whatever wraps the loader rejection before sanitizing picks up the auth classification somewhere else — fixing that mislabel independently would save users a lot of wasted `/login` cycles.

Repro of the underlying error (same as the issue body):

```bash
PI_CURSOR_SDK_EVENT_DEBUG=1 \
PI_CURSOR_SDK_EVENT_DEBUG_DIR=/tmp/pi-cursor-sdk-debug \
pi --model cursor/grok-4.6 --cursor-no-fast -p "Say ok only."
# errors.jsonl → ResolveMessage: Cannot find module '@cursor/sdk' from '.../pi-cursor-sdk/dist/cursor-sdk-runtime.js'
```

## Verified workaround (bundles + relative/file-URL imports)

I got turns passing end-to-end (`pi ... -p "Say ok only."` → `ok`) without touching pi itself, using rolldown (already present in pi-cursor-sdk's own node_modules):

1. Bundle self-contained ESM files into `dist/` with `{ platform: 'node', codeSplitting: false }`:
   - `node_modules/@cursor/sdk/dist/esm/index.js` → `dist/cursor-sdk-bundle.mjs`
   - `node_modules/@cursor/sdk/dist/esm/sqlite.js` → `dist/cursor-sdk-sqlite.mjs`
   - the three `@modelcontextprotocol/sdk` subpaths above → `dist/vendor-mcp-{server,streamable,types}.mjs`
2. Copy every numeric webpack chunk (`node_modules/@cursor/sdk/dist/esm/[0-9]*.js`) into `dist/` — `sqlite.js` resolves them via a computed `import("./" + id + ".js")`, and they are dependency-free.
3. Rewrite the three sites:
   - `loadCursorSdk()` → `import(pathToFileURL(resolve(here, "cursor-sdk-bundle.mjs")).href)` (a computed file:// URL survives the loader; bare specifiers do not)
   - `import("@cursor/sdk/sqlite")` → `import(new URL("cursor-sdk-sqlite.mjs", import.meta.url).href)`
   - the three MCP imports → `"./vendor-mcp-*.mjs"` relative specifiers (relative specifiers inside the package resolve fine; only bare ones fail)

Happy to open a PR if a bundled-fallback approach (or shipping prebuilt bundles per release) is something you'd want upstream — otherwise feel free to lift the recipe.

**Comment by fitchmultz** [comment]
Could you attach a minimal credential-free reproducer using the exact failing Pi launcher, with pi --version, node --version, bun --version if applicable, and whether Pi is a compiled Bun binary, bundled Node build, or npm installation? Please include the original error name/code/message/stack/cause from errors.jsonl before the generic auth message, plus the extension install path. Current bundled Node Pi 0.85.0 and unbundled npm Pi 0.84.0 can load the SDK, SQLite and MCP seams without a key, so we need the failing loader class rather than another auth retry. Do not share auth.json or API keys.
